### ISSUE TITLE
Jira module is failing if http status code is 201

### ISSUE THREAD

**Issue by offlinehoster** [ansible/ansible-modules-extras#2121] opened 2016-04-28 13:58 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Jira.py
##### ANSIBLE VERSION

```
2.0.2.0 (and earlier versions)
```
##### CONFIGURATION

default
##### OS / ENVIRONMENT

Ubuntu 16.04 LTS 64bit
##### SUMMARY

If you send a request to your JIRA and get a http status code 201 back, the jira.py module will fail, because it only allows 200 and 204.
##### STEPS TO REPRODUCE

Doing this curl command
`curl -D- -u username:password -X POST --data-binary @comment.json -H "Content-Type: application/json" https://your_jira_tld/rest/api/latest/issue/issue-1337/comment`
is bringing you 
`HTTP/1.1 201 Created`
With the ansible module jira.py would this fail with the information:
`fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "OK (unknown bytes)"}`
##### EXPECTED RESULTS

Expected by running ansible would be -> done - the job should run fine
##### ACTUAL RESULTS

As i told, jira module is returning an error because of returning 201 instead of 200 or 204

**Comment by sivel** [comment] 2016-04-28 14:37
Duplicate of https://github.com/ansible/ansible-modules-extras/pull/2115

**Comment by sivel** [comment] 2016-04-28 14:43
Closing since we have 2 open PRs for this

**Closed as completed by sivel** 2016-04-28 14:43 UTC
