### ISSUE TITLE
[mysql_replication] MASTER_PORT should not be quoted

### ISSUE THREAD

**Issue by ruudk** [ansible/ansible-modules-extras#289] opened 2015-02-26 17:47 UTC
When setting up a mysql_replication that has a different `master_port` I get the following error:
`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''3307',MASTER_USER='slave',`

The reason for this is that the port number is quoted:
https://github.com/ansible/ansible-modules-extras/blob/650d740a3a4da365af47090d143fa2cb7bfd2fff/database/mysql/mysql_replication.py#L345

I think it should be changed to integer.

Ansible: 1.8.4
Mysql version: 5.5.41

**Comment by ruudk** [comment] 2015-02-27 08:20
Would it be fixed with changing:
`chm.append("MASTER_PORT=%(master_port)s")`

into

`chm.append("MASTER_PORT=%(master_port)d")`

?

**Comment by dtest** [comment] 2015-03-12 02:12
By changing to 

```
chm.append("MASTER_PORT=%(master_port)d")
```

I get a different error:

```
TypeError: %d format: a number is required, not str
```

My original error was with the master_log_pos in 5.6 similar to this issue: https://github.com/ansible/ansible/issues/9756

So making the change to make it integer worked

```
if master_log_pos:
    chm.append("MASTER_LOG_POS=%(master_log_pos)s")
    chm_params['master_log_pos'] = int(master_log_pos)
```

So fixing the following options should work
- MASTER_PORT
- MASTER_CONNECT_RETRY
- MASTER_LOG_POS
- RELAY_LOG_POS

Cross-referencing the list of options that exist in the module with http://dev.mysql.com/doc/refman/5.6/en/change-master-to.html

**Comment by abadger** [comment] 2015-03-12 16:25
Hmmm... this should have been fixed in: https://github.com/ansible/ansible-modules-extras/issues/155  Can you test that this is still an issue in either a devel checkout or a stable-1.9 checkout?

**Comment by dtest** [comment] 2015-03-12 19:25
Confirmed, that fix works and is much cleaner. Cheers

**Comment by abadger** [comment] 2015-03-12 20:03
Excellent.  Thanks for testing!

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2015-03-12 20:03 UTC
Labels: P3, bug_report, needs_info
