### ISSUE TITLE
Possible Proprietary Module Distributed

### ISSUE THREAD

**Issue by hlieberman** [ansible/ansible-modules-extras#516] opened 2015-05-20 02:22 UTC
##### Issue Type:

Bug Report
##### Ansible Version:

git master
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

The module extras/database/postgresql/postgresql_lang.py has a copyright header, but has no licensing information.  As a result, it must be assumed to be proprietary -- and cannot be distributed with a GPLv3 package.

The license should be clarified or it should be removed.

**Comment by wenottingham** [comment] 2015-05-20 05:32
cc @jensdepuydt

**Comment by bcoca** [comment] 2015-06-01 19:25
closing as duplicate of #508

**Closed as completed by bcoca** 2015-06-01 19:25 UTC
Labels: P2, bug_report
