### ISSUE TITLE
nagios module - fail_json() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by ifelsefi** [ansible/ansible-modules-extras#1257] opened 2015-11-17 17:34 UTC
Using ansible 1.9.4

downtime.yml:

```
- hosts: "{{ hosts }}"
  become: yes
  become_user: prod
  roles:
    - downtime
```

Command:

```
ansible-playbook downtime.yml -e hosts=tusamgt1p02 -K
```

Task:

```
- name: Set Host Downtime - PROD
  nagios: service=host host={{ inventory_hostname }} action=downtime minutes=5
  delegate_to: "tusamon1p04"
```

Output:

```
debug1: control_persist_detach: backgrounding master process
debug1: forking to background
debug1: Entering interactive session.
debug1: multiplexing control connection
debug1: channel 1: new [mux-control]
debug1: channel 2: new [client-session]
debug1: mux_client_request_session: master session id: 2
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug1: Sending command: /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=yttysfvrxunacgkyvguiitlzvgmucsnl] password: " -u prod /bin/sh -c '"'"'echo BECOME-SUCCESS-yttysfvrxunacgkyvguiitlzvgmucsnl; LANG=C LC_CTYPE=C /usr/bin/python'"'"''
[sudo via ansible, key=yttysfvrxunacgkyvguiitlzvgmucsnl] password: Traceback (most recent call last):
  File "<stdin>", line 2504, in <module>
  File "<stdin>", line 230, in main
TypeError: fail_json() takes exactly 1 argument (2 given)
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 1: free: mux-control, nchannels 2
debug1: mux_client_request_session: master session id: 2

FATAL: all hosts have already failed -- aborting
```

Any idea?

Thanks

**Comment by robynbergeron** [comment] 2015-11-25 07:05
@JusticeForMikeBrown -- thanks for submitting this bug report. 

@tbielawa -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by robynbergeron** [comment] 2015-11-25 07:05
[module: monitoring/nagios.py]

**Comment by timlnx** [comment] 2015-11-25 15:28
It's really difficult to read your input files @JusticeForMikeBrown . Could you please format that with markdown styling, or put them into a gist?

It's really difficult to tell what's happening at all in your situation. Are you still able to reproduce the error?

**Comment by ifelsefi** [comment] 2015-11-30 16:39
Sorry, I am a n00b.

 # ansible command

`ansible-playbook ~/repos/playbooks/downtime.yml -e hosts=tusamgt1p02 -K`

 # downtime.yml 

```
- hosts: "{{ hosts }}"
  gather_facts: False
  become: yes
  become_user: prod
  roles:
    - downtime
```

  # ~/repos/playbooks/roles/downtime/tasks/main.yml

```
- name: Set Host Downtime - PROD
  nagios: service=host host={{ inventory_hostname }} action=downtime minutes=5
  delegate_to: "tusamon1p04"
```

 # error

```
debug1: Sending command: /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=msheisjpueugpeiptyuyanlypmeqziii] password: " -u prod /bin/sh -c '"'"'echo BECOME-SUCCESS-msheisjpueugpeiptyuyanlypmeqziii; LANG=C LC_CTYPE=C /usr/bin/python'"'"'' [sudo via ansible, key=msheisjpueugpeiptyuyanlypmeqziii] password: Traceback (most recent call last):
  File "<stdin>", line 2504, in <module>
  File "<stdin>", line 230, in main
TypeError: fail_json() takes exactly 1 argument (2 given)
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 1: free: mux-control, nchannels 2
debug1: mux_client_request_session: master session id: 2

FATAL: all hosts have already failed -- aborting
```

**Comment by bcoca** [comment] 2015-11-30 16:55
what version of ansible? pytnon? OS?

**Comment by ifelsefi** [comment] 2015-11-30 19:45
RHEL 6.7

Python 2.6.6

Ansible 1.9.4

**Comment by ifelsefi** [comment] 2015-11-30 19:47
Thanks for the markdown assistance!

**Comment by ifelsefi** [comment] 2015-12-02 20:34
So I need nagios.cfg!?

**Comment by bcoca** [comment] 2015-12-02 20:38
yep, that is probably why no one else saw that error

**Comment by bcoca** [comment] 2015-12-02 20:38
and that nagios config needs to have an entry for the command file

**Comment by ifelsefi** [comment] 2015-12-02 20:41
Thanks.  I am using Check_MK so this module probably will not work...

**Comment by bcoca** [comment] 2015-12-02 20:42
you can still have a nagios.cfg that points to the command file with check_mk

**Comment by mscherer** [comment] 2016-03-19 22:35
So, if I am not wrong, this bug can be closed, since the associated PR was merged. Please tell if the issue was wrongly closed.

**Closed as completed by mscherer** 2016-03-19 22:35 UTC
Labels: bug_report
