### ISSUE TITLE
codec can't encode characters in position 62759-6276

### ISSUE THREAD

**Issue by anthonygreen** [ansible/ansible-modules-extras#671] opened 2015-07-01 20:31 UTC
the task

```
- name: Install Python dependencies
  command: /usr/local/bin/pip install httplib2
  sudo: yes
```

fails with the error

```
msg: failed to create temporary content file: 'ascii' codec can't encode characters in position 62759-62760: ordinal not in range(128)
```

**Comment by bcoca** [comment] 2015-07-04 02:40
can you fill in the tempalte so we get enough info to try to debug this? https://github.com/ansible/ansible/blob/devel/ISSUE_TEMPLATE.md

**Comment by abadger** [comment] 2015-07-06 16:25
Unable to reproduce this locally:

```
$ cat test.yml                                                                       (09:25:00)
---
- hosts: localhost
  tasks:
  - name: Install Python dependencies
    command: /usr/bin/pip install httplib2
    sudo: yes

$ ansible-playbook test.yml -K -vvvv                                                 (09:22:06)
SUDO password: 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
<localhost> ESTABLISH CONNECTION FOR USER: badger
<localhost> REMOTE_MODULE setup
<localhost> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/badger/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 localhost /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
ok: [localhost]

TASK: [Install Python dependencies] ******************************************* 
<localhost> ESTABLISH CONNECTION FOR USER: badger
<localhost> REMOTE_MODULE command /usr/bin/pip install httplib2
<localhost> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/badger/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 localhost /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=irqrelleriznjkzrhsbtbgvcozirmwgo] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-irqrelleriznjkzrhsbtbgvcozirmwgo; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
changed: [localhost] => {"changed": true, "cmd": ["/usr/bin/pip", "install", "httplib2"], "delta": "0:00:03.369839", "end": "2015-07-06 09:22:14.955084", "rc": 0, "start": "2015-07-06 09:22:11.585245", "stderr": "", "stdout": "Downloading/unpacking httplib2\n  Running setup.py (path:/tmp/pip-build-IMDJwP/httplib2/setup.py) egg_info for package httplib2\n    \nInstalling collected packages: httplib2\n  Running setup.py install for httplib2\n    \nSuccessfully installed httplib2\nCleaning up...", "warnings": []}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by abadger** [comment] 2015-07-06 16:58
This fragment of the error message: `failed to create temporary content file:` does not occur in the command module error string.  It does occur in the get_url and uri modules.  The uri module uses httplib2 and it has an issue that I believe could easily provoke that message:  https://github.com/ansible/ansible/issues/10938  There's a fix for that in devel: https://github.com/ansible/ansible-modules-core/pull/1331

I was hoping to get testing on that before pushing to 1.9.x but no one has replied.  Since it's been several months I'll push this to stable-1.9 under the assumption that people would have complained if it caused a regression.  It will go into 1.9.3 assuming that no one finds any problems with it before then.  You can test it out earlier by downloading the new version of the module from the repository and using it.  https://raw.githubusercontent.com/ansible/ansible-modules-core/devel/network/basics/uri.py

**Comment by abadger** [comment] 2015-07-06 17:01
Pushed to stable1-.9: https://github.com/ansible/ansible-modules-core/commit/6906760d46b8afb884c5340415a17df315afd1b2

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed as completed by abadger** 2015-07-06 17:01 UTC
Labels: P3, bug_report, pending_action
