### ISSUE TITLE
F5 LTM Error: ansible requires the stdlib json or simplejson module, neither was found

### ISSUE THREAD

**Issue by carterfields** [ansible/ansible-modules-extras#2602] opened 2016-07-20 17:56 UTC
#### Issue Type:
- Bug Report
#### Component Name:

bigip_facts
#### Summary:

@mhite 
@caphrim007

I can't seem to get Ansible to talk to my F5 (BIG-IP 11.6.0 Build 6.0.442 Hotfix HF6).  I get: `error fatal: [f5ltm1.mydomain.com]: FAILED! => {"changed": false, "failed": true, "msg": "Error: ansible requires the stdlib json or simplejson module, neither was found!"}`

```

    ansible@ansible:~$ python -V
    Python 2.7.12
    ansible@ansible:~$ pip list | grep json
    simple-json (1.1)
    simplejson (3.3.1)
    ansible@ansible:~$ pip list | grep bigsuds
    bigsuds (1.0.4)
    ansible@ansible:~$ ansible --version
    ansible 2.1.0.0
      config file = /etc/ansible/ansible.cfg
      configured module search path = Default w/o overrides
```

I've tried two variations on the pb:

```
 ---
    # file bigip-test.yml
    # ...
    - hosts: loadbalancers
      tasks:
        - name: "Collect BIG-IP facts"
          bigip_facts:
            include: "interface,vlan"
            password: ansible
            server: f5ltm1.mydomain.com
            user: ansible
          delegate_to: localhost
```

and

```

---
    # file bigip-test.yml
    # ...
    - hosts: loadbalancers
      tasks:
      - name: Collect BIG-IP facts
        local_action: >
          bigip_facts
          server=f5ltm1.mydomain.com
          user=ansible
          password=ansible
          include=interface,vlan
```

YAML syntax has been validated locally, please ignore any issues here with syntax 

/etc/ansible/hosts:

```
    [loadbalancers]
    f5ltm1.mydomain.com
```

SSH & Ping to the LTM are also fine.

If anyone has had a similar problem and found a solution, please let me know.

**Comment by caphrim007** [comment] 2016-07-20 22:37
whats the output if you run the playbook with -vvvv ?

**Comment by carterfields** [comment] 2016-07-20 22:44
ansible@ansible:~$ ansible-playbook f5_test_1.yml -vvvv
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: f5_test_1.yml ********************************************************
1 plays in f5_test_1.yml

PLAY [loadbalancers] ***********************************************************

TASK [setup] *******************************************************************
<192.168.225.75> ESTABLISH SSH CONNECTION FOR USER: ansible
<192.168.225.75> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ansible/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.225.75 '/bin/sh -c '"'"'( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1469054480.69-206421060444542`" && echo ansible-tmp-1469054480.69-206421060444542="`echo $HOME/.ansible/tmp/ansible-tmp-1469054480.69-206421060444542`" ) && sleep 0'"'"''
<192.168.225.75> PUT /tmp/tmpkw7Fjm TO /home/ansible/.ansible/tmp/ansible-tmp-1469054480.69-206421060444542/setup
<192.168.225.75> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ansible/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r '[192.168.225.75]'
<192.168.225.75> ESTABLISH SSH CONNECTION FOR USER: ansible
<192.168.225.75> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ansible/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r -tt 192.168.225.75 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1469054480.69-206421060444542/setup; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1469054480.69-206421060444542/" > /dev/null 2>&1 && sleep 0'"'"''
fatal: [f5ltm1.mydomain.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "setup"}, "msg": "Error: ansible requires the stdlib json or simplejson module, neither was found!"}

NO MORE HOSTS LEFT *************************************************************
                to retry, use: --limit @f5_test_1.retry

PLAY RECAP *********************************************************************
f5ltm1.mydomain.com    : ok=0    changed=0    unreachable=0    failed=1

ansible@ansible:~$ cat f5_test_1.yml

## playbook task examples:

---

# file bigip-test.yml

# ...
- hosts: loadbalancers
  tasks:
  - name: Collect BIG-IP facts
    bigip_facts:
      server: "f5ltm1.mydomain.com"
      user: "ansible"
      password: "ansible"
      include: "interface,vlan"
    delegate_to: localhost

**Comment by mhite** [comment] 2016-07-21 00:33
Seems to be tripping up on the common module import:

https://github.com/ansible/ansible/blob/0a439df4b0a3173868884aa4778fd99ec80b505f/lib/ansible/module_utils/basic.py

```
try:
    import json
    # Detect the python-json library which is incompatible
    # Look for simplejson if that's the case
    try:
        if not isinstance(json.loads, types.FunctionType) or not isinstance(json.dumps, types.FunctionType):
            raise ImportError
    except AttributeError:
        raise ImportError
except ImportError:
    try:
        import simplejson as json
    except ImportError:
        print('\n{"msg": "Error: ansible requires the stdlib json or simplejson module, neither was found!", "failed": true}')
        sys.exit(1)
    except SyntaxError:
        print('\n{"msg": "SyntaxError: probably due to installed simplejson being for a different python version", "failed": true}')
        sys.exit(1)
```

This is a shot in the dark, but what's the difference between:

```
simple-json (1.1)
simplejson (3.3.1)
```

Also, do any modules work for you?

**Comment by caphrim007** [comment] 2016-07-21 00:53
@mhite @carterfields and everyone else, we managed to figure it out. the playbook needed the following

`gather_facts: false`

in it to ensure that its first step was to NOT reach out to BIG-IP to gather facts. There is no JSON library on the BIG-IP until version 12 and 11.6.x was in use in this case.

**Comment by mhite** [comment] 2016-07-21 18:13
Ah, good catch. I was wondering why the setup module was bombing out. 

The example playbooks in the module documentation could definitely be better. For example, the example playbook doesn't demonstrate using an actual load balancer from the inventory to drive what gets passed to the bigip_facts server parameter. Additionally, disabling of implicit Ansible fact gathering would be good to add also as you stumbled across.

Thoughts?

**Comment by gundalow** [comment] 2016-09-07 20:14
@mhite, @caphrim007 What would you like to do with this?

**Comment by caphrim007** [comment] 2016-09-07 20:49
@gundalow this is not a bug, just a usage error that needs to be documented. So we can close this now and I will address it offline

**Comment by gundalow** [comment] 2016-09-08 11:54
Closing as @caphrim007 suggested. Thanks for confirming.

**Closed as completed by gundalow** 2016-09-08 11:54 UTC
Labels: bug_report, networking, waiting_on_maintainer

**Comment by karthikm57** [comment] 2018-01-22 03:15
can you provide me usage document to test @caphrim007

**Comment by caphrim007** [comment] 2018-01-22 03:35
@karthikm57 if you are having an issue with something in Ansible devel related to F5 modules, I would suggest filing an issue here 

https://github.com/F5Networks/f5-ansible/issues
