### ISSUE TITLE
pacman module always reports meta package installation as 'changed'

### ISSUE THREAD

**Issue by sysfu** [ansible/ansible-modules-extras#649] opened 2015-06-28 20:03 UTC
Ansible 1.9.1

pacman module tasks that install either the 'base-devel' or 'gnome' meta packages always report the status as "changed" and "installed 1 package(s)". This occurs even though the meta package is already installed.

```
TASK: [workstations | install Arch software pkgs] ************************* 
ok: [host.name] => (item=kexec-tools) => {"changed": false, "item": "kexec-tools", "msg": "package(s) already installed"}
ok: [host.name] => (item=nfs-utils) => {"changed": false, "item": "nfs-utils", "msg": "package(s) already installed"}
changed: [host.name] => (item=base-devel) => {"changed": true, "item": "base-devel", "msg": "installed 1 package(s)"}
TASK: [workstations | install Gnome Desktop environment ] ********* 
changed: [host.name] => {"changed": true, "msg": "installed 1 package(s)"}
```

**Comment by bcoca** [comment] 2015-06-30 18:03
are these virtual or meta packages?

**Comment by bcoca** [comment] 2015-06-30 18:06
closing as dupe of #650

**Closed as completed by bcoca** 2015-06-30 18:06 UTC
Labels: P3, bug_report
