### ISSUE TITLE
win_lineinfile to modify hosts, it changes file permission so process can't read it

### ISSUE THREAD

**Issue by dbpeng** [ansible/ansible-modules-extras#1440] opened 2015-12-30 17:03 UTC
Does anyone have similar issue? 

I found others have this issue too in other thread https://github.com/ansible/ansible-modules-core/issues/2236

B

**Comment by robynbergeron** [comment] 2016-01-11 17:37
Hi @dbpeng --

win_lineinfile is a core module; can you please file this issue in the appropriate repository, so we can route it to the maintainer? :) Thanks! https://github.com/ansible/ansible-modules-core

**Comment by nitzmahone** [comment] 2016-02-11 17:42
duplicate of https://github.com/ansible/ansible-modules-core/issues/2236 - closing

**Closed as completed by nitzmahone** 2016-02-11 17:42 UTC
