### ISSUE TITLE
blockinfile: marker doesn't compare entire line

### ISSUE THREAD

**Issue by moralloki** [ansible/ansible-modules-extras#1968] opened 2016-04-05 17:39 UTC
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

blockinfile
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The marker directive doesn't compare the entire line when checking for blocks.  Similar blocks will be unintentionally overwritten breaking idempotency.
##### STEPS TO REPRODUCE

Can be reproduced from a tweak to one of the examples run 2+ times:

```
- name: insert/update hosts in /tmp/hosts
  blockinfile:
    dest: /tmp/hosts
    block: |
      {{item.name}} {{item.ip}}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{item.name}}"
  with_items:
      - { name: host, ip: 10.10.1.10 }
      - { name: host2, ip: 10.10.1.11 }
```

##### EXPECTED RESULTS

```
# BEGIN ANSIBLE MANAGED BLOCK host
host 10.10.1.10
# END ANSIBLE MANAGED BLOCK host
# BEGIN ANSIBLE MANAGED BLOCK host1
host1 10.10.1.11
# END ANSIBLE MANAGED BLOCK host1
```
##### ACTUAL RESULTS

```
# BEGIN ANSIBLE MANAGED BLOCK host
host 10.10.1.10
# END ANSIBLE MANAGED BLOCK host
# BEGIN ANSIBLE MANAGED BLOCK host
host 10.10.1.10
# END ANSIBLE MANAGED BLOCK host
# BEGIN ANSIBLE MANAGED BLOCK host1
host1 10.10.1.11
# END ANSIBLE MANAGED BLOCK host1
```

**Comment by moralloki** [comment] 2016-04-05 18:07
Due to work constraints, I cannot push a fix for this through proper channels so here it is:

```
*** files/blockinfile.py    2016-04-05 11:03:10.489771358 -0700
--- files/blockinfile.py.orig   2016-04-05 11:03:56.339775598 -0700
***************
*** 252,260 ****

      n0 = n1 = None
      for i, line in enumerate(lines):
!         if line == marker0:
              n0 = i
!         if line == marker1:
              n1 = i

      if None in (n0, n1):
--- 252,260 ----

      n0 = n1 = None
      for i, line in enumerate(lines):
!         if line.startswith(marker0):
              n0 = i
!         if line.startswith(marker1):
              n1 = i

      if None in (n0, n1):
```

**Comment by mavit** [comment] 2016-04-07 18:48
This is a duplicate of #1926.

**Comment by nitzmahone** [comment] 2016-04-28 18:12
closing, duplicate

**Closed as completed by nitzmahone** 2016-04-28 18:12 UTC
Labels: bug_report
